# Get all categories
GET http://localhost:3000/api/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzExMjI1NzQzLCJleHAiOjE3MTEyMjkzNDN9._7gSTk4G7vYVgxMjlRv5CbTeJ9Qb0F7Wzhnv6lNclak


# Get a category by id
GET http://localhost:3000/api/category/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzExMjI1NzQzLCJleHAiOjE3MTEyMjkzNDN9._7gSTk4G7vYVgxMjlRv5CbTeJ9Qb0F7Wzhnv6lNclak


# Create a category
POST http://localhost:3000/api/category
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzExMjI1NzQzLCJleHAiOjE3MTEyMjkzNDN9._7gSTk4G7vYVgxMjlRv5CbTeJ9Qb0F7Wzhnv6lNclak
content-type: application/json

{
  "name": "Category 1"
}


# Update a category
PATCH http://localhost:3000/api/category/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzExMjI1NzQzLCJleHAiOjE3MTEyMjkzNDN9._7gSTk4G7vYVgxMjlRv5CbTeJ9Qb0F7Wzhnv6lNclak
content-type: application/json

{
  "name": "Outside"
}


# Delete a category
DELETE http://localhost:3000/api/category/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzExMjI1NzQzLCJleHAiOjE3MTEyMjkzNDN9._7gSTk4G7vYVgxMjlRv5CbTeJ9Qb0F7Wzhnv6lNclak


